### PR TITLE
kodi: SIGTERM patch: do not delay shutdown

### PR DESCRIPTION
**Pull request by mglae**
When using poweroff from shutdown menu Kodi tries to delay systemd shutdown until application is stopped.

With SIGTERM patch we do wait for the term signal to stop application. This only does not dead lock because the delay is aborted after InhibitDelayMaxSec (defaulting to 5 sec).

```
kodi.log:
2019-04-11 23:23:43.726 T:140134077353280    INFO: Saving exitCode 64
2019-04-11 23:23:43.730 T:140134077353280   DEBUG: LogindUPowerSyscall - inhibit lock taken, fd 46
[...]
2019-04-11 23:23:49.471 T:140134077353280  NOTICE: Quitting due to POSIX signal
[...]
2019-04-11 23:23:51.228 T:140134077353280   DEBUG: LogindUPowerSyscall - delay lock shutdown released

journal:
Apr 11 23:23:48 le9mars systemd-logind[290]: Delay lock is active (UID 0/root, PID 895/kodi.bin) but inhibitor timeout is reached.
Apr 11 23:23:48 le9mars systemd-logind[290]: System is powering down.
```
Removing taking the inhibit lock allows starting shutting down without delay.

### CODE REVIEW

**Comment by MilhouseVH** [comment]
The thing is that Kodi should wait _up to_ 5 seconds if addons don't exit immediately - is this the issue? I'm not seeing these delays on my x86_64 system (as one example) but then I don't have many addons installed. We don't want to shut down Kodi without giving the addons a chance to terminate gracefully.

**Comment by mglae** [comment]
> The thing is that Kodi should wait _up to_ 5 seconds if addons don't exit immediately 

This is still the case after kodi have received the SIGTERM from systemd. But systemd delays the start of shutdown because of the taken delay lock. InhibitDelayMaxSec is  5 seconds too by chance and not the TimeoutStopSec parameter of the kodi.service.

In my sample poweroff is pressed at 23:23:43, systemd just waits until 23:23:48 to start system shutdown. Kodi is triggered at 23:23:49 having additional 5 sec to terminate gracefully.

You have to perform a shutdown, the delay lock is not taken when rebooting.

**Comment by MilhouseVH** [comment]
Thanks, this is in the latest nightly starting with `#0417`.

**Comment by MilhouseVH** [comment]
Added this to https://github.com/LibreELEC/LibreELEC.tv/pull/3424, which is now merged.

**Pull request closed without merging**
