### PR TITLE
get_git: fixes and enhancements

### PR DESCRIPTION
**Pull request by ToKe79**
- fix checking of downloaded repo
- enhance branch handling
- add commit checking on the branch (to not reset to a commit on different branch)

### CODE REVIEW

**Comment by MilhouseVH** [comment]
Have you thought about using a sub-process to avoid having to worry about returning to the original directory? For instance, `_get_repo_already_downloaded` would become:
```
_get_repo_already_downloaded() {
  if [ -d $PACKAGE ]; then
    (
      cd $PACKAGE
      _get_repo_clean
      [ "$PKG_VERSION" =  "$(git ls-remote . | grep HEAD | head -n 1 | awk '{print substr($1,1,7);}')" ] || exit 1
      [ "$PKG_URL" = "$(git remote get-url origin)" ] || exit 1
      [ -z "$PKG_GIT_CLONE_BRANCH" ] && exit 0
      [ "$PKG_GIT_CLONE_BRANCH" = "$(git branch | grep ^\* | cut -d ' ' -f2)" ] || exit 1
      exit 0
    )
    return
  else
    return 1
  fi
}
```
You could apply the same sub-process technique elsewhere, for instance [here](https://github.com/ToKe79/LibreELEC.tv/blob/cc59080575a47f8e43c22ca92ef351216a6d27af/scripts/get_git#L138-L143).

And for [here](https://github.com/ToKe79/LibreELEC.tv/blob/cc59080575a47f8e43c22ca92ef351216a6d27af/scripts/get_git#L138-L143) it might just be easier to stash the current directory before entering the `for` loop with `opwd=${PWD}` then return to that directory with `cd ${opwd}` instead of `cd - >/dev/null`, and again after exiting from the `for` loop so that you are back in the directory you started in and not some random git repository.

In addition,
```
      [ -n "$(git ls-remote . | grep -m1 HEAD | awk "/^${PKG_VERSION}/ {print \$1}")" ] || exit 1
```
could be used to replace:
```
      [ "$PKG_VERSION" =  "$(git ls-remote . | grep HEAD | head -n 1 | awk '{print substr($1,1,7);}')" ] || exit 1
```
and has the advantage of not matching on only len=7 (sometimes PKG_VERSION will need to be longer, eg. len=8, if there is another abbreviated hash with the same first 7 characters).

**Comment by ToKe79** [comment]
Thank you for your feedback - hopefully I understood all proposed changes. Based on your feedback I also changed a bit other parts - for now as separate commit and if you agree on the changes, I can squash them all into one.

**Comment by MilhouseVH** [comment]
Looks good, although this might be a simplification of the `for` loop: https://gist.github.com/MilhouseVH/7c4c265c102162b3b3b7cca9aeed2fa9/revisions 

I don't it should matter that you are deleting the current working directory, and it would always ensure you are back in the original directory once you leave the `for` loop (as it is, you may be left inside one of the git repositories that you are cleaning).

It's not a big deal, but being left in a random directory just ticks my OCD. :)

Can you squash the commits once you are done and then I'll add the commit and close this PR as I'd rather not have the merge commit in the LE master history.

**Comment by MilhouseVH** [comment]
Many thanks, closed via f97cd06

**Pull request closed without merging**
